import React from "react";
import ReactDOM from "react-dom/client";

const Header = () => {
  return (
    <nav id="header">
      <div id="image-container">
        <img
          id="logo"
          alt="logo"
          src="https://drive.google.com/uc?export=download&id=1PrOLgDbWl_W2l9ouvkz1RLvZiOsls2HJ"
        ></img>
      </div>
      <div>
        <ul id="nav-links">
          <li>Home</li>
          <li>Restaurants</li>
          <li>Your Orders</li>
          <li>About Us</li>
          <li>Cart</li>
        </ul>
      </div>
    </nav>
  );
};

const Search = () => {
  return <div></div>;
};

const Cards = (props) => {
  const { resData } = props;
  const { resName, cusines, ratings, deliveryTime, price } = resData;

  return (
    <div className="card">
      <img
        id="res-card-img"
        alt="card"
        src="https://images.unsplash.com/photo-1630851840633-f96999247032?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80"
      ></img>
      <h3 class="card-description">{resName}</h3>
      <p class="card-description">{cusines.join(", ")}</p>
      <div id="card-description-secondary" class="card-description">
        <span>{ratings + " ★"}</span>
        <span> • </span>
        <span>{deliveryTime + " minutes"}</span>
        <span> • </span>
        <span>{"₹ " + price}</span>
      </div>
    </div>
  );
};

const resList = [
  {
    cardType: "carousel",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "carousel",
      subtype: "topCarousel",
      data: {
        cards: [
          {
            type: "carouselElement",
            subtype: "image",
            data: {
              bannerId: 635529,
              creativeId: "rng/md/carousel/production/pneknawbadtvceqzwiep",
              type: "restaurantCollectionV2",
              link: "49301",
              cityId: 0,
              restaurantUuid: "",
              restaurantParentId: "0",
              thirdPartyVendor: "",
              thirdPartyAddress: false,
            },
          },
          {
            type: "carouselElement",
            subtype: "image",
            data: {
              bannerId: 304993,
              creativeId: "rng/md/carousel/production/lori508m4xps01tnywxf",
              type: "restaurantCollectionV2",
              link: "47670",
              cityId: 0,
              restaurantUuid: "",
              restaurantParentId: "0",
              thirdPartyVendor: "",
              thirdPartyAddress: false,
            },
          },
          {
            type: "carouselElement",
            subtype: "image",
            data: {
              bannerId: 619141,
              creativeId: "rng/md/carousel/production/zpkkdkmvlj5cuvqbc50t",
              type: "restaurantCollectionV2",
              link: "56413",
              cityId: 0,
              restaurantUuid: "",
              restaurantParentId: "0",
              thirdPartyVendor: "",
              thirdPartyAddress: false,
            },
          },
          {
            type: "carouselElement",
            subtype: "image",
            data: {
              bannerId: 619143,
              creativeId: "rng/md/carousel/production/lzkjv3sxwwjkzg0vxpvt",
              type: "restaurantCollectionV2",
              link: "56422",
              cityId: 0,
              restaurantUuid: "",
              restaurantParentId: "0",
              thirdPartyVendor: "",
              thirdPartyAddress: false,
            },
          },
          {
            type: "carouselElement",
            subtype: "image",
            data: {
              bannerId: 619142,
              creativeId: "rng/md/carousel/production/tgnvusbs3fnzz7xupeno",
              type: "restaurantCollectionV2",
              link: "56417",
              cityId: 0,
              restaurantUuid: "",
              restaurantParentId: "0",
              thirdPartyVendor: "",
              thirdPartyAddress: false,
            },
          },
          {
            type: "carouselElement",
            subtype: "image",
            data: {
              bannerId: 619145,
              creativeId: "rng/md/carousel/production/nhubtkw7dukg3ukcmpam",
              type: "restaurantCollectionV2",
              link: "56414",
              cityId: 0,
              restaurantUuid: "",
              restaurantParentId: "0",
              thirdPartyVendor: "",
              thirdPartyAddress: false,
            },
          },
          {
            type: "carouselElement",
            subtype: "image",
            data: {
              bannerId: 607188,
              creativeId: "rng/md/carousel/production/oxe97jexxbnxqtbhg2zo",
              type: "restaurantCollectionV2",
              link: "11740",
              cityId: 0,
              restaurantUuid: "",
              restaurantParentId: "0",
              thirdPartyVendor: "",
              thirdPartyAddress: false,
            },
          },
          {
            type: "carouselElement",
            subtype: "image",
            data: {
              bannerId: 607195,
              creativeId: "rng/md/carousel/production/ifi2lbzxeu1hvsqrsip3",
              type: "restaurantCollectionV2",
              link: "56421",
              cityId: 0,
              restaurantUuid: "",
              restaurantParentId: "0",
              thirdPartyVendor: "",
              thirdPartyAddress: false,
            },
          },
        ],
      },
    },
    parentWidget: false,
  },
  {
    cardType: "carousel",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "carousel",
      subtype: "openFilter",
      data: {
        cards: [
          {
            type: "carouselElement",
            subtype: "image",
            data: {
              bannerId: 181684,
              creativeId: "bkhjfipzydkoqncrxpyi",
              type: "restaurantCollectionV2",
              link: "11718",
              cityId: 0,
              restaurantUuid: "",
              restaurantParentId: "0",
              title: "Offers Near You",
              subtitle: "0 OPTIONS",
              restaurants: [],
              totalCount: 0,
              dwebOpenFilterTitle: "Offers Near You",
              dwebOpenFilterBgColor: "#FF0000",
              dwebOpenFilterSelectIcon: "eyperwsfhaoa5vktjtu4",
              dwebOpenFilterDeselectIcon: "urw8usdf4mk9aywd59gq",
            },
          },
          {
            type: "carouselElement",
            subtype: "image",
            data: {
              bannerId: 181680,
              creativeId: "a3jqjjod5taken7dh1bs",
              type: "restaurantCollectionV2",
              link: "11721",
              cityId: 0,
              restaurantUuid: "",
              restaurantParentId: "0",
              title: "Veg Only",
              subtitle: "0 OPTIONS",
              restaurants: [],
              totalCount: 0,
              dwebOpenFilterTitle: "Vegetarian Options",
              dwebOpenFilterBgColor: "#FF0000",
              dwebOpenFilterSelectIcon: "qtjc8dzfexg72lug37a0",
              dwebOpenFilterDeselectIcon: "bm8bziikwyvwqsml1clm",
            },
          },
        ],
      },
    },
    parentWidget: false,
  },
  {
    cardType: "seeAllRestaurants",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "seeAllRestaurants",
      data: {
        title: "SEE ALL",
        totalOpenRestaurants: 170,
        cards: [
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "715108",
              name: "Hotel Sunrise",
              uuid: "7e11430b-dcf4-4afc-96ec-249aaeca022d",
              city: "57",
              area: "Khandagiri",
              totalRatingsString: "50+ ratings",
              cloudinaryImageId: "dc5264445465769eac73535cb6006a1a",
              cuisines: [
                "Indian",
                "North Indian",
                "Hyderabadi",
                "Tandoor",
                "Chinese",
                "Biryani",
                "Snacks",
              ],
              tags: [],
              costForTwo: 30000,
              costForTwoString: "₹300 FOR TWO",
              deliveryTime: 46,
              minDeliveryTime: 46,
              maxDeliveryTime: 46,
              slaString: "46 MINS",
              lastMileTravel: 6.599999904632568,
              slugs: {
                restaurant: "hotel-sunrise-khandagiri-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "18/2491,Khandagiri  Vihar,Khandagiri,Bhubaneswar,  BHUBANESWAR MUNICIPAL CORPORATION,  Orissa-751030",
              locality: "Municipal Corporation",
              parentId: 102810,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              ribbon: [
                {
                  type: "PROMOTED",
                },
              ],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 5400,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 5400,
                message: "",
                title: "Delivery Charge",
                amount: "5400",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID:
                "cid=6873486~p=1~eid=00000188-e70d-f8e1-00d6-0f1400c70155~srvts=1687503632609",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "6.5 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "40% OFF",
                subHeader: "UPTO ₹80",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "715108",
                deliveryTime: 46,
                minDeliveryTime: 46,
                maxDeliveryTime: 46,
                lastMileTravel: 6.599999904632568,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: true,
              avgRating: "4.5",
              totalRatings: 50,
              new: true,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "101033",
              name: "Burger King",
              uuid: "2bd495da-48be-4afa-b192-7a8304beb542",
              city: "57",
              area: "Kalinga Vihar",
              totalRatingsString: "10000+ ratings",
              cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
              cuisines: ["Burgers", "American"],
              tags: [],
              costForTwo: 35000,
              costForTwoString: "₹350 FOR TWO",
              deliveryTime: 29,
              minDeliveryTime: 29,
              maxDeliveryTime: 29,
              slaString: "29 MINS",
              lastMileTravel: 2.299999952316284,
              slugs: {
                restaurant: "burger-king-dn-regalia-mall-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "Burger King, FC 101, First floor, DN Regalia Mall,Service Rd S, Kalinga Vihar, Patrapada, Bhubaneswar, Odisha,751019",
              locality: "Kalinga Vihar",
              parentId: 166,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 2600,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 2600,
                message: "",
                title: "Delivery Charge",
                amount: "2600",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "2.2 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "60% OFF",
                subHeader: "UPTO ₹120",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "101033",
                deliveryTime: 29,
                minDeliveryTime: 29,
                maxDeliveryTime: 29,
                lastMileTravel: 2.299999952316284,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "4.4",
              totalRatings: 10000,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "443672",
              name: "Pizza Hut",
              uuid: "531ab018-ab1b-4ca6-b54f-c8dac475e737",
              city: "57",
              area: "DN Regalia",
              totalRatingsString: "1000+ ratings",
              cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
              cuisines: ["Pizzas"],
              tags: [],
              costForTwo: 35000,
              costForTwoString: "₹350 FOR TWO",
              deliveryTime: 32,
              minDeliveryTime: 32,
              maxDeliveryTime: 32,
              slaString: "32 MINS",
              lastMileTravel: 1.7000000476837158,
              slugs: {
                restaurant: "pizza-hut-regalia-mall-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "Pizza Hut, DN Regalia, Shop No-109, 1/A, IDCO Industrial Area, DN Squre, Patrapada, Bhubaneswar, Ward 65, BHUBANESWAR MUNICIPAL CORPORATION, Orissa, 751019",
              locality: "DN Squre",
              parentId: 721,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 2600,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 2600,
                message: "",
                title: "Delivery Charge",
                amount: "2600",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "1.7 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "50% OFF",
                subHeader: "UPTO ₹100",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "443672",
                deliveryTime: 32,
                minDeliveryTime: 32,
                maxDeliveryTime: 32,
                lastMileTravel: 1.7000000476837158,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "4.0",
              totalRatings: 1000,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "118941",
              name: "Keshari Garnish",
              uuid: "e5e4cec0-c3d0-4de7-a4e6-f1fc20a86d05",
              city: "57",
              area: "Jagmohan Nagar",
              totalRatingsString: "10000+ ratings",
              cloudinaryImageId: "oco4kvkl6q8myvnkxkul",
              cuisines: ["Indian", "Chinese", "Tandoor", "Biryani"],
              tags: [],
              costForTwo: 25000,
              costForTwoString: "₹250 FOR TWO",
              deliveryTime: 41,
              minDeliveryTime: 41,
              maxDeliveryTime: 41,
              slaString: "41 MINS",
              lastMileTravel: 7.099999904632568,
              slugs: {
                restaurant: "keshari-garnish-jagamara-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address: "Plot no-1088,Jagamara,Jagmohan Nagar,Khandagiri",
              locality: "Jagamara",
              parentId: 116605,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              ribbon: [
                {
                  type: "PROMOTED",
                },
              ],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 6100,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 6100,
                message: "",
                title: "Delivery Charge",
                amount: "6100",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID:
                "cid=7152441~p=4~eid=00000188-e70d-f8e1-00d6-0f1500c70448~srvts=1687503632609",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "7 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "60% OFF",
                subHeader: "UPTO ₹120",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "118941",
                deliveryTime: 41,
                minDeliveryTime: 41,
                maxDeliveryTime: 41,
                lastMileTravel: 7.099999904632568,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: true,
              avgRating: "3.8",
              totalRatings: 10000,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "718220",
              name: "Paneer Singh & Chicken Khurana",
              uuid: "b451c88c-dc24-4d7e-b37d-c55f0eb123a3",
              city: "57",
              area: "Klinga Vihar",
              totalRatingsString: "Too Few Ratings",
              cloudinaryImageId: "057cfc7a242cd3e1c029f19bca216c27",
              cuisines: ["North Indian", "Kebabs", "Biryani", "Mughlai"],
              tags: [],
              costForTwo: 50000,
              costForTwoString: "₹500 FOR TWO",
              deliveryTime: 46,
              minDeliveryTime: 46,
              maxDeliveryTime: 46,
              slaString: "46 MINS",
              lastMileTravel: 1.7000000476837158,
              slugs: {
                restaurant: "paneer-singh-chicken-khurana-patrapada-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "SHOP NO 105, 1st FLOOR, KALINGA VIHAR, PATRAPADA, BHUBANESWAR,ODISA - 751019",
              locality: "PATRAPADA",
              parentId: 428197,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 2600,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 2600,
                message: "",
                title: "Delivery Charge",
                amount: "2600",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "1.7 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "50% OFF",
                subHeader: "UPTO ₹100",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "718220",
                deliveryTime: 46,
                minDeliveryTime: 46,
                maxDeliveryTime: 46,
                lastMileTravel: 1.7000000476837158,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "--",
              totalRatings: 0,
              new: true,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "436806",
              name: "Vaango",
              uuid: "f74cbb44-a2de-487a-8dda-eee2750bdb92",
              city: "57",
              area: "Patrapada",
              totalRatingsString: "500+ ratings",
              cloudinaryImageId: "k8hl3eymuddgpp2pnkr3",
              cuisines: ["South Indian"],
              tags: [],
              costForTwo: 40000,
              costForTwoString: "₹400 FOR TWO",
              deliveryTime: 36,
              minDeliveryTime: 36,
              maxDeliveryTime: 36,
              slaString: "36 MINS",
              lastMileTravel: 1.7000000476837158,
              slugs: {
                restaurant: "vaango-khandagiri-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "VAANGO, Shop No-FC-108, DN Regalia,1/A IDCO, Industrial Area, Bhagabanpur, DN Square, Patra Pada, Bhubaneswar,, Ward 65, BHUBANESWAR MUNICIPAL CORPORATION, Orissa-751019",
              locality: "Dn Regalia",
              parentId: 2364,
              unserviceable: false,
              veg: true,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 2600,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 2600,
                message: "",
                title: "Delivery Charge",
                amount: "2600",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "1.7 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "₹125 OFF",
                subHeader: "ABOVE ₹499",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "436806",
                deliveryTime: 36,
                minDeliveryTime: 36,
                maxDeliveryTime: 36,
                lastMileTravel: 1.7000000476837158,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "4.3",
              totalRatings: 500,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "97254",
              name: "Scholars",
              uuid: "15393e00-5fa6-4f06-b769-601f830716ee",
              city: "57",
              area: "Jagmohan Nagar",
              totalRatingsString: "10000+ ratings",
              cloudinaryImageId: "msgcyfeduwjljoahj2fv",
              cuisines: ["Indian", "Biryani", "Kebabs", "Chinese"],
              tags: [],
              costForTwo: 20000,
              costForTwoString: "₹200 FOR TWO",
              deliveryTime: 41,
              minDeliveryTime: 41,
              maxDeliveryTime: 41,
              slaString: "41 MINS",
              lastMileTravel: 7.300000190734863,
              slugs: {
                restaurant:
                  "scholars-jagmohan-nagar-near-iter-campus-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "Plot 1735/3933, Near ITER College Main Gate, Jagmohan Nagar, Bhubaneshwar",
              locality: "Iter College Road",
              parentId: 9640,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              ribbon: [
                {
                  type: "PROMOTED",
                },
              ],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 6100,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 6100,
                message: "",
                title: "Delivery Charge",
                amount: "6100",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID:
                "cid=7152272~p=7~eid=00000188-e70d-f8e1-00d6-0f1600c7073e~srvts=1687503632609",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "7.3 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "₹125 OFF",
                subHeader: "ABOVE ₹349",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "97254",
                deliveryTime: 41,
                minDeliveryTime: 41,
                maxDeliveryTime: 41,
                lastMileTravel: 7.300000190734863,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: true,
              avgRating: "3.9",
              totalRatings: 10000,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "377064",
              name: "Keventers Ice Cream",
              uuid: "b0dd0706-bfdb-4b3e-bc4f-bd6b0f903560",
              city: "57",
              area: "Patrapada",
              totalRatingsString: "100+ ratings",
              cloudinaryImageId: "5220cf2d5049dd54b0fb98bbb3d5a652",
              cuisines: ["Ice Cream", "Desserts"],
              tags: [],
              costForTwo: 20000,
              costForTwoString: "₹200 FOR TWO",
              deliveryTime: 23,
              minDeliveryTime: 23,
              maxDeliveryTime: 23,
              slaString: "23 MINS",
              lastMileTravel: 1.7000000476837158,
              slugs: {
                restaurant:
                  "keventers-ice-creamery-d-n-regalia-mall-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "KEVENTERS (A unit of SUPER MILK PRODUCTS PVT LTD) FIRST FLOOR, FOOD COURT, KIOSK NO FK-106,D.N. REGALIA BHUBNESWAR,ODISHA-751019",
              locality: "Dn Regalia Road",
              parentId: 272044,
              unserviceable: false,
              veg: true,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 2600,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 2600,
                message: "",
                title: "Delivery Charge",
                amount: "2600",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "1.7 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "20% OFF",
                subHeader: "UPTO ₹50",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "377064",
                deliveryTime: 23,
                minDeliveryTime: 23,
                maxDeliveryTime: 23,
                lastMileTravel: 1.7000000476837158,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "4.3",
              totalRatings: 100,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "396090",
              name: "KFC",
              uuid: "f52dbbea-f191-4e8e-9bc3-f3a50cc5b760",
              city: "57",
              area: "Patrapada",
              totalRatingsString: "1000+ ratings",
              cloudinaryImageId: "56c9ab92bd79745fd152a30fa2525426",
              cuisines: [
                "Burgers",
                "Biryani",
                "American",
                "Snacks",
                "Fast Food",
              ],
              tags: [],
              costForTwo: 40000,
              costForTwoString: "₹400 FOR TWO",
              deliveryTime: 27,
              minDeliveryTime: 27,
              maxDeliveryTime: 27,
              slaString: "27 MINS",
              lastMileTravel: 2.299999952316284,
              slugs: {
                restaurant: "kfc-regalia-mall-bbsr-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "Food Court DN Regalia Mall , Service Road South Tamando,D N Square, kalinga Bihar, Patrapada, Bhubaneshwar, Odisha -751019",
              locality: "DN Square",
              parentId: 547,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 2600,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 2600,
                message: "",
                title: "Delivery Charge",
                amount: "2600",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "2.2 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "40% OFF",
                subHeader: "UPTO ₹80",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "396090",
                deliveryTime: 27,
                minDeliveryTime: 27,
                maxDeliveryTime: 27,
                lastMileTravel: 2.299999952316284,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "4.1",
              totalRatings: 1000,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "245592",
              name: "Cloud Kitchen",
              uuid: "477138e8-b941-4716-83c2-a576b7a5f825",
              city: "57",
              area: "Khandagiri",
              totalRatingsString: "10000+ ratings",
              cloudinaryImageId: "do4eceyqvlo4jjeistrm",
              cuisines: ["Chinese", "Biryani", "North Indian", "Tandoor"],
              tags: [],
              costForTwo: 30000,
              costForTwoString: "₹300 FOR TWO",
              deliveryTime: 52,
              minDeliveryTime: 52,
              maxDeliveryTime: 52,
              slaString: "52 MINS",
              lastMileTravel: 6.900000095367432,
              slugs: {
                restaurant: "cloud-kitchen-khandagiri-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "AMLAN JYOTI DAS,PLOT NO-K-8/683,KALINGA NAGAR,GHATIKIA,BHUBANESWAR, Ward 23, BHUBANESWAR MUNICIPAL CORPORATION(Orissa) -751003",
              locality: "Kalinga Nagar",
              parentId: 7687,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              ribbon: [
                {
                  type: "PROMOTED",
                },
              ],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 5400,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 5400,
                message: "",
                title: "Delivery Charge",
                amount: "5400",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID:
                "cid=7152438~p=10~eid=00000188-e70d-f8e1-00d6-0f1700c70a23~srvts=1687503632609",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "6.9 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "60% OFF",
                subHeader: "UPTO ₹120",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "245592",
                deliveryTime: 52,
                minDeliveryTime: 52,
                maxDeliveryTime: 52,
                lastMileTravel: 6.900000095367432,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: true,
              avgRating: "4.0",
              totalRatings: 10000,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "447798",
              name: "Barbeque Nation",
              uuid: "7c32f889-4c3c-4a70-9964-9409db914a3b",
              city: "57",
              area: "Patrapada",
              totalRatingsString: "500+ ratings",
              cloudinaryImageId: "su2rbe3m6cvam4ha573e",
              cuisines: [
                "North Indian",
                "Barbecue",
                "Biryani",
                "Kebabs",
                "Mughlai",
                "Desserts",
              ],
              tags: [],
              costForTwo: 60000,
              costForTwoString: "₹600 FOR TWO",
              deliveryTime: 56,
              minDeliveryTime: 56,
              maxDeliveryTime: 56,
              slaString: "56 MINS",
              lastMileTravel: 2.299999952316284,
              slugs: {
                restaurant:
                  "barbeque-nation-service-road-south-tamando-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "Barbeque Nation Hospitality Limited 6th Floor, Service Road South Tamando, DN Square,  Kalinga Vihar, Patrapada, Odisha 751019",
              locality: "Dn Squre",
              parentId: 2438,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 2600,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 2600,
                message: "",
                title: "Delivery Charge",
                amount: "2600",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "2.2 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "40% OFF",
                subHeader: "UPTO ₹80",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "447798",
                deliveryTime: 56,
                minDeliveryTime: 56,
                maxDeliveryTime: 56,
                lastMileTravel: 2.299999952316284,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "3.8",
              totalRatings: 500,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "685062",
              name: "Kathi Nation",
              uuid: "6dd84e30-eb9a-48c7-bd9e-96a3c5386ec6",
              city: "57",
              area: "DN REGALIA",
              totalRatingsString: "Too Few Ratings",
              cloudinaryImageId: "1583be9e51c080b8af55101ceaf31502",
              cuisines: ["Snacks", "Burgers", "Fast Food", "Beverages"],
              tags: [],
              costForTwo: 45000,
              costForTwoString: "₹450 FOR TWO",
              deliveryTime: 42,
              minDeliveryTime: 42,
              maxDeliveryTime: 42,
              slaString: "42 MINS",
              lastMileTravel: 1.7000000476837158,
              slugs: {
                restaurant: "kathination-khandagiri-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "FC-102 & FK-006, DN REGALIA, PLOT NO.-1/A, BHAGABANPUR INDUSTRIAL ESTATE, DN SQUARE, PATRAPADA, Ward 65, BHUBANESWAR MUNICIPAL CORPORATION, Orissa-751019",
              locality: "Patrapada",
              parentId: 115628,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 2600,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 2600,
                message: "",
                title: "Delivery Charge",
                amount: "2600",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "1.7 kms",
              hasSurge: false,
              sla: {
                restaurantId: "685062",
                deliveryTime: 42,
                minDeliveryTime: 42,
                maxDeliveryTime: 42,
                lastMileTravel: 1.7000000476837158,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "--",
              totalRatings: 0,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "391383",
              name: "Dil-E-Mughlai",
              uuid: "66e42a0c-0a38-4682-a0e9-4c30e6eaede3",
              city: "57",
              area: "Khandagiri",
              totalRatingsString: "1000+ ratings",
              cloudinaryImageId: "yeu8blahmwaxsvokdr8a",
              cuisines: [
                "Mughlai",
                "Biryani",
                "Chinese",
                "Tandoor",
                "Oriental",
              ],
              tags: [],
              costForTwo: 30000,
              costForTwoString: "₹300 FOR TWO",
              deliveryTime: 43,
              minDeliveryTime: 43,
              maxDeliveryTime: 43,
              slaString: "43 MINS",
              lastMileTravel: 7.599999904632568,
              slugs: {
                restaurant: "dil-e-mughlai-khandagiri-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "PLOT NO-1199, JAGAMARA, PO/PSKHAANDAGIRI, BHUBANESWAR, ITER College, Ward 64, BHUBANESWAR MUNICIPAL CORPORATION, Orissa - 751030",
              locality: "Jagamara",
              parentId: 244819,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              ribbon: [
                {
                  type: "PROMOTED",
                },
              ],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 6100,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 6100,
                message: "",
                title: "Delivery Charge",
                amount: "6100",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID:
                "cid=7152443~p=13~eid=00000188-e70d-f8e1-00d6-0f1800c70d37~srvts=1687503632609",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "7.5 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "20% OFF",
                subHeader: "UPTO ₹50",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "391383",
                deliveryTime: 43,
                minDeliveryTime: 43,
                maxDeliveryTime: 43,
                lastMileTravel: 7.599999904632568,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: true,
              avgRating: "4.2",
              totalRatings: 1000,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "175745",
              name: "Keventers - Milkshakes & Desserts",
              uuid: "9654a153-2f91-498a-a90f-da1cd6f21a44",
              city: "57",
              area: "Patrapada",
              totalRatingsString: "1000+ ratings",
              cloudinaryImageId: "af8216b15abde417bb0e1d8fc44fb877",
              cuisines: ["Beverages", "Ice Cream", "Desserts", "Healthy Food"],
              tags: [],
              costForTwo: 20000,
              costForTwoString: "₹200 FOR TWO",
              deliveryTime: 26,
              minDeliveryTime: 26,
              maxDeliveryTime: 26,
              slaString: "26 MINS",
              lastMileTravel: 2.299999952316284,
              slugs: {
                restaurant: "keventers-regalia-mall-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "FIRST FLOOR, UNIT NO KIOSK FK 106,DN REGALIA MALL, BHUBNESWAR, ODISHA, 751019",
              locality: "Dn Regalia Mall",
              parentId: 268997,
              unserviceable: false,
              veg: true,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 2600,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 2600,
                message: "",
                title: "Delivery Charge",
                amount: "2600",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "2.2 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "40% OFF",
                subHeader: "UPTO ₹80",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "175745",
                deliveryTime: 26,
                minDeliveryTime: 26,
                maxDeliveryTime: 26,
                lastMileTravel: 2.299999952316284,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "4.3",
              totalRatings: 1000,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "352385",
              name: "7/12 Fried Ice Cream Parlour",
              uuid: "68b1db51-2ea5-4b5b-bf74-ea017712bbcb",
              city: "57",
              area: "Patrapada",
              totalRatingsString: "20+ ratings",
              cloudinaryImageId: "dyvpken3obmo9oj1yynd",
              cuisines: ["Ice Cream", "Desserts", "Beverages"],
              tags: [],
              costForTwo: 25000,
              costForTwoString: "₹250 FOR TWO",
              deliveryTime: 46,
              minDeliveryTime: 46,
              maxDeliveryTime: 46,
              slaString: "46 MINS",
              lastMileTravel: 1.7000000476837158,
              slugs: {
                restaurant: "7/12-fried-ice-cream-khandagiri-khandagiri",
                city: "bhubaneswar",
              },
              cityState: "57",
              address:
                "DN Regalia, DN Square, Kalinga Vihar, Patrapada, Bhubaneswar, Odisha, India",
              locality: "Kalinga Vihar",
              parentId: 387898,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 2600,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 2600,
                message: "",
                title: "Delivery Charge",
                amount: "2600",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "1.7 kms",
              hasSurge: false,
              sla: {
                restaurantId: "352385",
                deliveryTime: 46,
                minDeliveryTime: 46,
                maxDeliveryTime: 46,
                lastMileTravel: 1.7000000476837158,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "3.7",
              totalRatings: 20,
              new: false,
            },
            subtype: "basic",
          },
        ],
        totalRestaurants: 170,
      },
      subtype: "personalized",
    },
    parentWidget: false,
  },
];

const Body = () => {
  return (
    <div id="card-container">
      <Cards resData={resList[0]} />
      <Cards resData={resList[1]} />
      <Cards resData={resList[2]} />
    </div>
  );
};

const AppLayout = () => {
  return (
    <>
      <Header />
      <Search />
      <Body />
    </>
  );
};

const root = ReactDOM.createRoot(document.getElementById("root"));

root.render(<AppLayout />);
